MyWebApp/Controllers/CondoController.cs
using Microsoft.AspNetCore.Mvc;
using MyWebApp.Models;
using Newtonsoft.Json;

namespace MyWebApp.Controllers
{
	public class CondoController : Controller
	{
		public UserModel GetSessionInfo()
		{
			try
			{
				if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userSession")))
				{
					UserModel? user = JsonConvert.DeserializeObject<UserModel>(HttpContext.Session.GetString("userSession"));

					if (user.Type.Equals("root"))
					{
						return user;
					}
				}

				return null;
			}
			catch
			{
				return null;
			}
		}

		public ActionResult Main()
		{
			UserModel? user = GetSessionInfo();

			if (user != null)
			{
				ViewBag.User = user;
				return View();
			}
			
			return RedirectToAction("Index", "Error");			
		}

		// GET: CondoController
		public ActionResult Index()
		{
			UserModel? user = GetSessionInfo();

			if (user != null)
			{
				ViewBag.User = user;

				List<Condominium> condoList = CondominiumHelper.getCondominiums().Result;

				ViewBag.Condominium = condoList;

				HttpContext.Session.SetString("condoList", JsonConvert.SerializeObject(condoList));

				return View();
			}

			return RedirectToAction("Index", "Error");	
		}

		// GET: CondoController/Create
		public ActionResult Create()
		{
			UserModel? user = GetSessionInfo();

			if (user != null)
			{
				return View();
			}

			return RedirectToAction("Index", "Error");
		}

		public ActionResult CreateCondominium(string txtName, string txtAddress, int txtCount, string txtPhoto)
		{
			UserModel? user = GetSessionInfo();

			if (user != null)
			{
				bool result = CondominiumHelper.saveCondominium(new Condominium
				{
					Name = txtName,
					Address = txtAddress,
					Count = txtCount,
					Photo = txtPhoto
				}).Result;

				return RedirectToAction("Index");
			}

			return RedirectToAction("Index", "Error");
		}			

		// GET: CondoController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// POST: CondoController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: CondoController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: CondoController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: CondoController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: CondoController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

MyWebApp/Views/Condo/Create.cshtml
@{
	ViewData["Title"] = "Login Page";
}


<div class="container mt-4">
	<a class="btn btn-primary" asp-area="" asp-controller="Condo" asp-action="Index">Back</a>
	<hr />
	<div class="row justify-content-center">
		<div class="col-md-4">
			<div class="card shadow-lg p-4">
				<form method="post" asp-controller="Condo" asp-action="CreateCondominium">
					<div class="mb-3">
						<label for="txtName" class="form-label">Name</label>
						<input type="text" id="txtName" name="txtName" class="form-control" required />
					</div>
					<div class="mb-3">
						<label for="txtAddress" class="form-label">Address</label>
						<input type="text" id="txtAddress" name="txtAddress" class="form-control" required />
					</div>
					<div class="mb-3">
						<label for="txtCount" class="form-label">Count</label>
						<input type="number" id="txtCount" name="txtCount" class="form-control" required />
					</div>
					<div class="mb-3">
						<label for="txtPhoto" class="form-label">Photo</label>
						<input type="text" id="txtPhoto" name="txtPhoto" class="form-control" required />
					</div>
					<button type="submit" class="btn btn-primary w-100">Save</button>
				</form>
			</div>
		</div>
	</div>
</div>

MyWebApp/Views/Condo/Index.cshtml
@{
	ViewData["Title"] = "Login Page";
}


<div class="container mt-4">
	<h2>Condominium List - Welcome @ViewBag.User.Name</h2>
	<a class="btn btn-primary" asp-area="" asp-controller="Condo" asp-action="Main">Back</a>
	<a class="btn btn-primary" asp-area="" asp-controller="Condo" asp-action="Create">Add Condominium</a>
	<hr />
	<div class="row justify-content-center">
		@foreach (var condominium in ViewBag.Condominium)
		{
			<div class="col-md-4">
				<div class="card shadow-lg p-4">
					<img src="@condominium.Photo" style="width:22rem;height:18rem">
					<h2 class="text-center mb-4">@condominium.Name</h2>
					<div class="text-center mt-3">Count: @condominium.Count</div>
					<div class="text-center mt-3">Address: @condominium.Address</div>
				</div>
			</div>
		}
	</div>
</div>

MyWebApp/Views/Condo/Main.cshtml
@{
	ViewData["Title"] = "Login Page";
}


<div class="container mt-4">
	<h2>Root Main Page - Welcome @ViewBag.User.Name</h2>
	<hr />
	<div class="row justify-content-center">
		<div class="col-md-4">
			<div class="card shadow-lg p-4">
				<a asp-action="Index" asp-controller="Condo" class="text-center mb-4">See Condominium List</a>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card shadow-lg p-4">
				<a asp-action="Index" asp-controller="Condo" class="text-center mb-4">See Officer List</a>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card shadow-lg p-4">
				<a asp-action="Index" asp-controller="Profile" class="text-center mb-4">See Condominium Owners</a>
			</div>
		</div>
	</div>
</div>